# core/foia_constants.py

STATE_CITATIONS = {
    "Alabama": "Pursuant to the provisions of the Alabama Public Records Law, Ala. Code Section 36-12-40, 36-12-41.",
    "Alaska": "Pursuant to the provisions of the Alaska Public Records Act, Alaska Stat. Section 40.25.110-40.25.125, 40.25.151.",
    "Arizona": "Pursuant to the provisions of the Arizona Public Records Law, Ariz. Rev. Stat. Section 39-121.01 to 39-121.03.",
    "Arkansas": "Pursuant to the provisions of the Arkansas Freedom of Information Act, Ark. Code Ann. Section 25-19-101 to 25-19-111.",
    "California": "Pursuant to the provisions of the California Public Records Act, Cal. Gov’t Code Section 7920.000 to 7931.000.",
    "Colorado": "Pursuant to the provisions of the Colorado Open Records Act, Colo. Rev. Stat. Section 24-72-200.1 to 24-72-205.5.",
    "Connecticut": "Pursuant to the provisions of the Connecticut Freedom of Information Act, Conn. Gen. Stat. Section 1-200 to 1-242.",
    "Delaware": "Pursuant to the provisions of the Delaware Freedom of Information Act, Del. Code tit. 29, Section 10001-10007, 10112.",
    "Florida": "Pursuant to the provisions of the Florida Sunshine Law, Fla. Stat. Section 119.01 to 119.19.",
    "Georgia": "Pursuant to the provisions of the Georgia Open Records Act, Ga. Code Ann. Section 50-18-70 to 50-18-103.",
    "Hawaii": "Pursuant to the provisions of the Hawaii Uniform Information Practices Act (Modified), Haw. Rev. Stat. Section 92F-1 to 92F-43.",
    "Idaho": "Pursuant to the provisions of the Idaho Public Records Act, Idaho Code Section 74-101 to 74-126.",
    "Illinois": "Pursuant to the provisions of the Illinois Freedom of Information Act, 5 ILCS 140/1 to 140/11.6.",
    "Indiana": "Pursuant to the provisions of the Indiana Access to Public Records Act, Ind. Code Section 5-14-3-1 to 5-14-3-10.",
    "Iowa": "Pursuant to the provisions of the Iowa Open Records Law, Iowa Code Section 22.1 to 22.16.",
    "Kansas": "Pursuant to the provisions of the Kansas Open Records Act, Kan. Stat. Ann. Section 45-215 to 45-524.",
    "Kentucky": "Pursuant to the provisions of the Kentucky Open Records Act, Ky. Rev. Stat. Section 61.870 to 61.884.",
    "Louisiana": "Pursuant to the provisions of the Louisiana Public Records Law, La. Rev. Stat. Section 44:31 to 44:41.",
    "Maine": "Pursuant to the provisions of the Maine Freedom of Access Act, Me. Rev. Stat. tit. 1, Section 400 to 434.",
    "Maryland": "Pursuant to the provisions of the Maryland Public Information Act, Md. Code, Gen. Prov. Section 4-101 to 4-601.",
    "Massachusetts": "Pursuant to the provisions of the Massachusetts Public Records Law, Mass. Gen. Laws ch. 66, Section 1 to 21.",
    "Michigan": "Pursuant to the provisions of the Michigan Freedom of Information Act, Mich. Comp. Laws Section 15.231 to 15.246.",
    "Minnesota": "Pursuant to the provisions of the Minnesota Data Practices Act, Minn. Stat. Section 13.01 to 13.99.",
    "Mississippi": "Pursuant to the provisions of the Mississippi Public Records Act, Miss. Code Ann. Section 25-61-1 to 25-61-19.",
    "Missouri": "This request is made pursuant to Missouri’s Sunshine Law, Mo. Rev. Stat. Section 610.010 to 610.225.",
    "Montana": "Pursuant to the provisions of the Montana Public Records Act, Mont. Code Ann. Section 2-6-101 to 2-6-1020.",
    "Nebraska": "Pursuant to the provisions of the Nebraska Public Records Law, Neb. Rev. Stat. Section 84-712 to 84-712.09.",
    "Nevada": "Pursuant to the provisions of the Nevada Open Records Act, Nev. Rev. Stat. Section 239.010 to 239.340.",
    "New Hampshire": "This request is made pursuant to New Hampshire’s Right-to-Know Law, N.H. Rev. Stat. Ann. Section 91-A:1 to 91-A:10.",
    "New Jersey": "Pursuant to the provisions of the New Jersey Open Public Records Act, N.J. Stat. Ann. Section 47:1A-1 to 47:1A-13.",
    "New Mexico": "Pursuant to the provisions of the New Mexico Inspection of Public Records Act, N.M. Stat. Ann. Section 14-2-1 to 14-2-12.",
    "New York": "Pursuant to the provisions of the New York Freedom of Information Law, N.Y. Pub. Off. Law Section 84 to 90.",
    "North Carolina": "Pursuant to the provisions of the North Carolina Public Records Law, N.C. Gen. Stat. Section 132-1 to 132-11.",
    "North Dakota": "This request is made pursuant to North Dakota’s Open Records Statute, N.D. Cent. Code Section 44-04-18 to 44-04-32.",
    "Ohio": "Pursuant to the provisions of the Ohio Open Records Law, Ohio Rev. Code Section 149.43 to 149.45 and 2743.75.",
    "Oklahoma": "Pursuant to the provisions of the Oklahoma Open Records Act, Okla. Stat. tit. 51, Section 24A.1 to 24A.32.",
    "Oregon": "Pursuant to the provisions of the Oregon Public Records Law, Or. Rev. Stat. Section 192.311 to 192.513.",
    "Pennsylvania": "This request is made pursuant to Pennsylvania’s Right-to-Know Law, 65 Pa. Stat. Section 67.101 to 67.1310.",
    "Rhode Island": "Pursuant to the provisions of the Rhode Island Access to Public Records Act, R.I. Gen. Laws Section 38-2-1 to 38-2-16.",
    "South Carolina": "Pursuant to the provisions of the South Carolina Freedom of Information Act, S.C. Code Ann. Section 30-4-10 to 30-4-165.",
    "South Dakota": "Pursuant to the provisions of the South Dakota Sunshine Law, S.D. Codified Laws Section 1-27-1 to 1-27-48.",
    "Tennessee": "Pursuant to the provisions of the Tennessee Open Records Act, Tenn. Code Ann. Section 10-7-503 to 10-7-508.",
    "Texas": "Pursuant to the provisions of the Texas Public Information Act, Tex. Gov’t Code Section 552.001 to 552.376.",
    "Utah": "Pursuant to the provisions of the Utah Government Records Access and Management Act, Utah Code Ann. Section 63G-2-101 to 63G-2-804.",
    "Vermont": "Pursuant to the provisions of the Vermont Public Records Law, Vt. Stat. Ann. tit. 1, Section 315 to 320.",
    "Virginia": "Pursuant to the provisions of the Virginia Freedom of Information Act, Va. Code Ann. Section 2.2-3700 to 2.2-3715.",
    "Washington": "Pursuant to the provisions of the Washington Public Records Act, Wash. Rev. Code Section 42.56.001 to 42.56.904.",
    "West Virginia": "Pursuant to the provisions of the West Virginia Freedom of Information Act, W. Va. Code Section 29B-1-1 to 29B-1-7.",
    "Wisconsin": "Pursuant to the provisions of the Wisconsin Open Records Law, Wis. Stat. Section 19.21 to 19.39.",
    "Wyoming": "Pursuant to the provisions of the Wyoming Sunshine Law, Wyo. Stat. Ann. Section 16-4-201 to 16-4-205.",
}

STATE_RESPONSE_TIMES = {
    "Alabama": "We expect an acknowledgment within 10 business days and a full response within 15 business days pursuant to the Alabama Open Records Act. (Agencies may extend in 15-day increments with written notice.)",
    "Alaska": "I look forward to receiving your written response within 10 working days (i.e. business days) pursuant to the Alaska Public Records Act. (Alaska allows a one-time extension of up to 10 additional working days in unusual circumstances.)",
    "Arizona": "We expect a prompt response pursuant to the Arizona Public Records Law, which requires records to be furnished “promptly” (quickly, without unreasonable delay).",
    "Arkansas": "I look forward to receiving your written response within 3 working days pursuant to the Arkansas Freedom of Information Act.",
    "California": "I look forward to receiving your written response within 10 days pursuant to the California Public Records Act. (In unusual circumstances, an extension of up to 14 additional days is allowed.)",
    "Colorado": "I look forward to receiving your written response within 3 working days pursuant to the Colorado Open Records Act. (Extenuating circumstances can justify an extension up to 7 working days with notice.)",
    "Connecticut": "We expect a prompt response pursuant to the Connecticut Freedom of Information Act, which requires agencies to provide records “promptly” (considering factors like the agency’s workload and the request’s complexity).",
    "Delaware": "I look forward to receiving your written response within 15 business days pursuant to the Delaware Freedom of Information Act. (If records cannot be provided within 15 days, the agency must explain why and give an estimated availability date.)",
    "Florida": "We expect a prompt acknowledgment and good-faith response pursuant to the Florida Public Records Act, which mandates that requests be acknowledged promptly and responded to in good faith.",
    "Georgia": "I look forward to receiving your written response within 3 business days pursuant to the Georgia Open Records Act. (Within that period the agency must provide the records or a timeline for their later release.)",
    "Hawaii": "We expect an acknowledgment within 10 business days and, if the request cannot be completed immediately, a final response within 20 business days after that, pursuant to Hawaii’s Uniform Information Practices Act.",
    "Idaho": "I look forward to receiving your written response within 3 business days pursuant to the Idaho Public Records Act. (If more time is needed, the agency must so inform the requester in writing within 3 days, and may take up to 10 business days total to produce the records.)",
    "Illinois": "I look forward to receiving your written response within 5 business days pursuant to the Illinois Freedom of Information Act. (A one-time extension of 5 additional business days is permitted under specific circumstances.)",
    "Indiana": "I look forward to receiving your written response within 24 hours for in-person or telephone requests, or within 7 calendar days for written requests, pursuant to the Indiana Access to Public Records Act.",
    "Iowa": "I look forward to receiving your written response within 10 business days (and no more than 20 calendar days) pursuant to the Iowa Open Records Law. (The law requires records to be provided promptly, and any delay over 10 business days is presumed unreasonable absent extraordinary circumstances.)",
    "Kansas": "I look forward to receiving your written response within 3 business days pursuant to the Kansas Open Records Act.",
    "Kentucky": "I look forward to receiving your written response within 5 business days pursuant to the Kentucky Open Records Act.",
    "Louisiana": "I look forward to receiving your written response within 3 business days pursuant to the Louisiana Public Records Act (Louisiana Revised Statutes 44:32).",
    "Maine": "We expect an acknowledgment within 5 working days pursuant to the Maine Freedom of Access Act. (The agency’s acknowledgment may include an estimate of time needed to fully fulfill the request.)",
    "Maryland": "I look forward to receiving your written response within 30 calendar days pursuant to the Maryland Public Information Act. (If an agency needs more than 10 business days to gather records, it must send an interim letter within 10 days explaining the delay and a reasonable time estimate.)",
    "Massachusetts": "I look forward to receiving your written response within 10 business days pursuant to the Massachusetts Public Records Law.",
    "Michigan": "I look forward to receiving your written response within 5 business days pursuant to the Michigan Freedom of Information Act. (The agency may take a single extension of up to 10 additional business days with written notice.)",
    "Minnesota": "I look forward to receiving your written response within a reasonable time pursuant to the Minnesota Government Data Practices Act, which requires an agency to respond “within a reasonable amount of time” to public records requests.",
    "Mississippi": "I look forward to receiving your written response within 7 working days pursuant to the Mississippi Public Records Act. (Agencies may extend the time by an additional 7 working days with written notice, if needed to fulfill the request.)",
    "Missouri": "I look forward to receiving your written response within 3 business days pursuant to the Missouri Sunshine Law. (If an immediate response is not possible, the custodian must within 3 days provide a written explanation and timeline for when the records will be available.)",
    "Montana": "We expect a timely response pursuant to Montana law, which requires agencies to respond in a timely manner (promptly, without undue delay) to public information requests.",
    "Nebraska": "I look forward to receiving your written response within 4 business days pursuant to Nebraska public records statutes. (If a request cannot be fulfilled within 4 business days, the agency must provide a written explanation and estimate of how much additional time is needed.)",
    "Nevada": "I look forward to receiving your written response within 5 business days pursuant to the Nevada Public Records Act.",
    "New Hampshire": "I look forward to receiving your written response within 5 business days pursuant to the New Hampshire Right-to-Know Law. (Within five business days, the agency must either provide the records, deny the request in writing, or acknowledge receipt and indicate when the records will be available.)",
    "New Jersey": "I look forward to receiving your written response within 7 business days pursuant to the New Jersey Open Public Records Act.",
    "New Mexico": "I look forward to receiving your written response within 15 calendar days pursuant to New Mexico’s Inspection of Public Records Act. (New Mexico law also requires a prompt initial response; failure to respond at all within 15 days is deemed a denial.)",
    "New York": "I look forward to receiving your written response within 5 business days pursuant to the New York Freedom of Information Law. (Within that time the agency must grant the request, deny it, or acknowledge receipt and give an estimated date for a full response.)",
    "North Carolina": "We expect a prompt response pursuant to the North Carolina Public Records Law, which mandates that custodians respond “as promptly as possible” under the circumstances.",
    "North Dakota": "We expect a prompt response pursuant to North Dakota’s open records law, which requires agencies to respond within a reasonable time and without unreasonable delay.",
    "Ohio": "We expect a prompt response pursuant to the Ohio Public Records Act, which requires that records be made available “promptly” (without delay) and within a reasonable period of time.",
    "Oklahoma": "We expect a prompt response pursuant to the Oklahoma Open Records Act. Oklahoma law does not specify an exact number of days, but agencies are required to provide records “promptly” and in a reasonable time frame.",
    "Oregon": "We expect an acknowledgment within 5 business days and a full response within 15 business days (i.e. within 10 days after acknowledgment) pursuant to the Oregon Public Records Law.",
    "Pennsylvania": "I look forward to receiving your written response within 5 business days pursuant to Pennsylvania’s Right-to-Know Law. (An agency may invoke a single extension of up to 30 additional calendar days with written notice when necessary.)",
    "Rhode Island": "I look forward to receiving your written response within 10 business days pursuant to Rhode Island’s Access to Public Records Act. (A one-time extension of up to 20 business days is allowed for good cause.)",
    "South Carolina": "I look forward to receiving your written response within 10 business days pursuant to the South Carolina Freedom of Information Act. (If the requested records are more than 24 months old, the Act allows up to 20 business days for a response.)",
    "South Dakota": "I look forward to receiving your written response within 10 business days pursuant to South Dakota’s open records procedures. (State agencies generally must grant, deny, or acknowledge a records request within ten business days.)",
    "Tennessee": "I look forward to receiving your written response within 7 business days pursuant to the Tennessee Public Records Act. (Within seven business days the records custodian must either produce the records, deny the request in writing, or furnish a notice of the time needed to produce the records.)",
    "Texas": "I look forward to receiving your written response within 10 business days pursuant to the Texas Public Information Act. (By the 10th business day, a governmental body must either release the records, assert any exemptions (and seek an Attorney General’s ruling if applicable), or communicate when and how it will comply.)",
    "Utah": "I look forward to receiving your written response within 10 business days pursuant to Utah’s Government Records Access and Management Act (GRAMA). (Utah agencies must approve or deny a request within 10 business days, or 5 business days if an expedited response is granted.)",
    "Vermont": "I look forward to receiving your written response within 3 business days pursuant to the Vermont Public Records Act (which defines “promptly” as within three business days). (If an agency needs more time, it may invoke an extension of up to 7 business days in writing.)",
    "Virginia": "I look forward to receiving your written response within 5 working days pursuant to the Virginia Freedom of Information Act. (Virginia allows a 7-working-day extension beyond the initial 5-day period, if needed, with written notice to the requester.)",
    "Washington": "I look forward to receiving your written response within 5 business days pursuant to the Washington Public Records Act. (Within five business days, an agency must either provide the records, deny the request, or acknowledge receipt and give a reasonable estimate for completing the request.)",
    "West Virginia": "I look forward to receiving your written response within 5 business days pursuant to the West Virginia Freedom of Information Act.",
    "Wisconsin": "We expect a prompt response pursuant to the Wisconsin Open Records Law, which requires responses to be provided “as soon as practicable and without delay.” (While no fixed days are mandated by statute, delays must be reasonable under the circumstances.)",
    "Wyoming": "We expect an initial response within 7 business days and release of the requested records within 30 calendar days pursuant to the Wyoming Public Records Act. (Agencies may extend beyond 30 days only upon mutual agreement with the requester or by court order for good cause.)",
}
