INTRO_EXAMPLE = """
On the early morning of April 1, 2022, John Doe was performing his duties as a commercial truck driver when, while lawfully driving within the lane and within the speed limit, his tire caught an unmarked open patch which protruded over the center dashline into the lane of travel. This manmade patch was created and controlled by Defendants Acme Construction, RoadWorks LLC, Highway Solutions Inc., and AsphaltCo. Evidence will show, through video evidence from Plaintiff Doe’s dash camera, the testimony of an eyewitness who watched Plaintiff Doe’s driving for approximately 20 miles leading up to the crash, the conflicting testimony between the Defendants regarding their traffic control policies, and the testimony of the employee who was tasked with traffic control, that the Defendants were negligent at minimum. Defendants acted with a conscious disregard for the safety of drivers passing through the construction zone.
Mr. Doe’s damages are catastrophic and permanent. Plaintiff will not work again and will need in excess of $xxx,xxx,xxx in future medical care related to his traumatic brain injury and other injuries. Mr. Doe has undergone, and will continue to undergo, extensive treatment for a variety of injuries. Treatment resulting from this incident includes cervical and lumbar radiculopathy, traumatic brain injury, post-concussion syndrome, and post-traumatic stress disorder. His care included over 90 chiropractic sessions, multiple epidural steroid injections, inpatient hospitalization, and ultimately spinal decompression surgery. In addition to chronic physical pain, Mr. Doe suffers from cognitive decline, insomnia, and persistent psychological trauma. Specialists across neurology, orthopedics, psychiatry, and physical therapy have confirmed that his impairments are permanent and significantly restrict his ability to perform basic daily functions. Mr. Doe will not work for the rest of his career.
Plaintiff, Doe and his wife, Mrs. Zhang will request in excess of $xxx,xxx,xxx at trial – let alone co-Plaintiff’s trial ask. We will itemize this below. The defendants have disclosed that they maintain applicable insurance policies totaling $xxx,xxx,xxx covering the Subject Incident and all claims brought because of it.
"""

PLAINTIFF_STATEMENT_EXAMPLE = """
On April 1, 2022, John Doe was driving a commercial truck West Bound on Interstate 70 in Bond County at approximately 1:00am, when he approached a construction zone near Mile Marker 38. After slowing down and moving into the left lane, as the right lane was closed for construction, and entering the construction zone, Mr. Doe’s commercial truck was suddenly ripped off of the road, flipped over, and crashed into the tree line. Upon review, it was determined that the accident was caused by an unmarked portion of an open patch which protruded across the center dashline and into the lane of travel. As a result of this crash, Mr. Doe sustained life altering injuries to his neck and back. Imaging confirmed multiple cervical and lumbar disc protrusions, along with spinal stenosis and nerve impingement. Mr. Doe also exhibited signs of traumatic brain injury, including memory loss, impaired focus, and emotion dysregulation. As a result of these injuries, he has undergone a variety of treatment, including, but not limited to physical therapy, injections, chiropractic treatment, electrical shock therapy, and prescription pain medication.
At the time of collision, Mr. Doe worked as a licensed commercial truck driver. He had been driving commercially for three years since receiving his commercial driver’s license in 2019. Since the date of the crash, Mr. Doe has been unable to work as a commercial truck driver. Mr. Doe continues to be treated for neck and back pain. He will continue to require physical therapy, pain medication, and injections.
Plaintiff, Jane Smith
Jane Smith, age 53, is the wife of Plaintiff John Doe. Until the date of the incident, Mrs. Smith relied on Mr. Doe for income. Due to Mr. Doe’s inability to work, Ms. Smith has suffered a substantial loss in income in the household. Further, Mr. Doe has not been able to contribute to the household in other non-income related ways, including cooking, cleaning, and a general decrease in his ability to provide love and care for his family. This has caused further stress on Mr. Doe and Ms. Smith’s children, as they also relied on Mr. Doe for financial support and assistance, and now have to work while attending school to ensure that they can afford the cost of living.
"""

DEFENDANT_STATEMENT_EXAMPLE = """
On April 1, 2022, Acme Construction, a road construction and highway rehabilitation company, was overseeing the aforementioned construction zone as a sub-contractor. Acme had been responsible for maintaining control of the worksite portion of the interstate during the project. Until the date of the incident, Acme Construction had been in charge of the digging, and the hole which would eventually be the cause for Mr. Doe’s injury was dug by Acme.
At all relevant times, Acme Construction had a duty to take any necessary actions to prevent any person or persons such as Plaintiffs from being harmed by all manmade excavations, trenches, or cutouts near the worksite. Additionally, Acme had a duty to ensure that traffic could flow through the worksite in a safe and practical manner or close the road to traffic entirely. It was Acme's responsibility to affirmatively place the drums to protect drivers, like John Doe, in the open lane of traffic.
Acme staffed multiple employees on this project both on-site and in a managerial capacity. The cut out in the roadway was not adequately marked so as to warn vehicles on the roadway of its protrusion into traffic, and a severe accident occurred as a result. The Acme defendants are seemingly unwilling, even after reviewing accident footage, to acknowledge that barrel placement may be inadequate. On other occasions, they maintain that there is nothing negligent regarding their placement.
It is this cut out in the road that, coupled with Acme’s negligent handling of the construction site resulted in Plaintiff injuries.
There remain multiple inconsistencies in Acme Defendant statements, each varies either asserting that the safety barrels were in the right place, or that “wind” caused them to shift over, or that there was no safety issue in the first place.
Acme Construction prides themselves on safety, the team seemingly holds each other accountable, but on April 1, 2022, their failure to act, their failure to embody their safety “mantra,” directly led to John Doe’s injuries.
"""

DEMAND_EXAMPLE = """
The total applicable insurance coverage between these two Defendants that is potentially available to resolve all claims arising out of the Subject Incident is $xxx,xxx,xxx.
"""

FACTS_LIABILITY_EXAMPLE = """
In the early morning of April 1, 2022, John Doe was operating a commercial semi-tractor trailer westbound on I-70 in Bond County near the 38-mile mark. Around the area of the 38-mile mark, there was a construction zone containing several open patches. After lowering his speed, and staying within his own lane, Mr. Doe’s right tire caught the edge of one of these open patches, which protruded into the left lane, which was the active lane of travel. The 90-degree drop-off in the open patch, which was about 8 to 10 inches over the center divider and 18 to 20 inches deep, caused Mr. Doe’s truck to be ripped off the highway and into the tree line at an approximately 45-degree angle.
The barrel closest to the lane of travel left a substantial amount of this open patch unmarked. The cutout in the road protruded into the traffic lane, and yet, even when reviewing the footage, some of the defendants deny the existence of such. It is this cut out in the road that, coupled with the defendants’ negligent handling of the construction site resulted in Plaintiff injuries.
"""

CAUSATION_EXAMPLE = """
As a result of this occurrence, Mr. Doe will require lifelong pain management, ongoing cognitive rehabilitation, and lumbar microdiscectomy surgery, and has undergone extensive treatment across multiple specialties for life-altering injuries stemming from the Subject Incident. Mr. Doe reports that his conditions remain symptomatic and cause ongoing disability.
On April 1, 2022, Mr. Doe was a contract truck driver operating in the left lane of Interstate 70 when his vehicle struck an unmarked open patch in the road, flipping violently into the tree line. Following the collision, Mr. Doe experienced acute neck and back pain, dizziness, cognitive dysfunction, and psychological trauma.
Over the next year, Mr. Doe underwent 92 chiropractic sessions to address spinal stenosis and multilevel disc protrusions in both his cervical and lumbar spine. Despite conservative care, his symptoms worsened, prompting referrals for diagnostic imaging and pain management.
Ultimately, on February 29, 2024, Mr. Doe underwent a left L4-5 and L5-S1 hemilaminectomy and decompression. Despite the surgical intervention, Mr. Doe’s neurological deficits and pain symptoms remained significant, warranting continued rehabilitation and further evaluation.
As of the date of this submission, Mr. Doe continues to treat with multiple specialists across orthopedics, neurology, physical therapy, and pain management. Despite undergoing lumbar decompression surgery and extensive care, he continues to experience persistent cervical and lumbar pain, paresthesia, cognitive impairment, and psychological distress.
"""

HARMS_EXAMPLE = """
Following the motor vehicle collision on April 1, 2022, Mr. Doe has experienced a range of medical issues. Additionally, Mr. Doe suffered from lumbar radiculopathy, cervical disc protrusion, spinal stenosis, closed head injury, and traumatic spondyloarthropathy, among other severe medical conditions.
In addition to the physical toll, the collision profoundly impacted Mr. Doe's emotional and psychological well-being. He experienced anxiety, fearful thoughts, sleep disturbances, and concentration issues. He was diagnosed with post-traumatic stress disorder, and memory and cognitive decline.
Furthermore, Mr. Doe's daily function and quality of life have been severely compromised. He continues to experience head, neck, and back pain, memory difficulties, and challenges returning to work. These emotional injuries are not invisible. Mr. Doe’s family has watched him deteriorate. He cries more easily, avoids conversation, and no longer engages in lighthearted interactions or family traditions. His emotional wounds, like his physical ones, are permanent.
"""

FUTURE_BILLS_EXAMPLE = """
Mr. Doe's ongoing symptoms require lifelong pain management. The anticipated cost of these procedures, encompassing follow-up physical therapy, imaging, and medication, is expected to continue over his lifetime.
An expert has come up with an opinion that Mr. Doe will incur in excess of $xxx,xxx,xxx in future medical due to his injuries related to this crash.
"""

CONCLUSION_EXAMPLE = """
The clear and conscious disregard for the Plaintiff’s safety, along with the safety of all other drivers passing through the construction zone under the control of the Defendants demonstrates their clear liability for this crash. Plaintiff’s significant past and future medical bills, combined with the ongoing pain and suffering, and the substantial effect on his family demonstrate significant risk for the defendants of an award from a jury exceeding the policy limits in this matter.
"""
